'use client';

import { useReducer, useEffect, useRef, useCallback } from 'react';
import type { ExamPhase, PrepNotes, DiscussionMessage, AIEvaluation } from '@/lib/types';

const PREP_DURATION = 10 * 60; // 600 seconds

// ─── State shape ─────────────────────────────────────────────
export interface ExamState {
  phase: ExamPhase;
  prepSecondsLeft: number;
  prepNotes: PrepNotes;
  audioBlob: Blob | null;
  audioUrl: string | null;          // Object URL for local playback
  transcript: string | null;
  allQuestions: string[];           // Pre-generated by Claude, served sequentially
  questionIndex: number;
  discussionMessages: DiscussionMessage[];
  evaluation: AIEvaluation | null;
  isLoading: boolean;
  loadingMessage: string;
  error: string | null;
}

// ─── Action Union ─────────────────────────────────────────────
type Action =
  | { type: 'TICK_PREP' }
  | { type: 'ADVANCE_TO_READY' }
  | { type: 'START_RECORDING' }
  | { type: 'FINISH_RECORDING'; payload: { blob: Blob; url: string } }
  | { type: 'SET_LOADING'; payload: { on: boolean; message?: string } }
  | { type: 'SET_TRANSCRIPT'; payload: string }
  | { type: 'INIT_DISCUSSION'; payload: { questions: string[] } }
  | { type: 'SUBMIT_STUDENT_ANSWER'; payload: string }
  | { type: 'ADVANCE_QUESTION' }
  | { type: 'SET_EVALUATION'; payload: AIEvaluation }
  | { type: 'COMPLETE' }
  | { type: 'UPDATE_NOTES'; payload: Partial<PrepNotes> }
  | { type: 'SET_ERROR'; payload: string };

// ─── Initial state ────────────────────────────────────────────
const initial: ExamState = {
  phase: 'prep',
  prepSecondsLeft: PREP_DURATION,
  prepNotes: { phenomenon: '', causes: '', impacts: '', solutions: '' },
  audioBlob: null,
  audioUrl: null,
  transcript: null,
  allQuestions: [],
  questionIndex: 0,
  discussionMessages: [],
  evaluation: null,
  isLoading: false,
  loadingMessage: '',
  error: null,
};

// ─── Reducer ──────────────────────────────────────────────────
function reducer(state: ExamState, action: Action): ExamState {
  switch (action.type) {
    case 'TICK_PREP':
      if (state.prepSecondsLeft <= 1) {
        return { ...state, prepSecondsLeft: 0, phase: 'ready_to_record' };
      }
      return { ...state, prepSecondsLeft: state.prepSecondsLeft - 1 };

    case 'ADVANCE_TO_READY':
      return { ...state, phase: 'ready_to_record' };

    case 'START_RECORDING':
      return { ...state, phase: 'recording' };

    case 'FINISH_RECORDING':
      return {
        ...state,
        phase: 'processing',
        audioBlob: action.payload.blob,
        audioUrl: action.payload.url,
        isLoading: true,
        loadingMessage: '正在上传录音...',
      };

    case 'SET_LOADING':
      return {
        ...state,
        isLoading: action.payload.on,
        loadingMessage: action.payload.message ?? '',
      };

    case 'SET_TRANSCRIPT':
      return { ...state, transcript: action.payload, loadingMessage: '正在生成考官问题...' };

    case 'INIT_DISCUSSION': {
      const [first, ...rest] = action.payload.questions;
      const examinerOpening: DiscussionMessage = {
        role: 'examiner',
        content: first,
        timestamp: new Date().toISOString(),
        questionIndex: 0,
      };
      return {
        ...state,
        phase: 'discussion',
        isLoading: false,
        loadingMessage: '',
        allQuestions: action.payload.questions,
        questionIndex: 0,
        discussionMessages: [examinerOpening],
      };
    }

    case 'SUBMIT_STUDENT_ANSWER': {
      const studentMsg: DiscussionMessage = {
        role: 'student',
        content: action.payload,
        timestamp: new Date().toISOString(),
      };
      return {
        ...state,
        discussionMessages: [...state.discussionMessages, studentMsg],
        isLoading: true,
        loadingMessage: '考官正在思考...',
      };
    }

    case 'ADVANCE_QUESTION': {
      const nextIndex = state.questionIndex + 1;
      if (nextIndex >= state.allQuestions.length) {
        // All questions answered — trigger evaluation
        return { ...state, isLoading: true, loadingMessage: '正在生成综合评估报告...' };
      }
      const nextQ = state.allQuestions[nextIndex];
      const nextMsg: DiscussionMessage = {
        role: 'examiner',
        content: nextQ,
        timestamp: new Date().toISOString(),
        questionIndex: nextIndex,
      };
      return {
        ...state,
        questionIndex: nextIndex,
        discussionMessages: [...state.discussionMessages, nextMsg],
        isLoading: false,
        loadingMessage: '',
      };
    }

    case 'SET_EVALUATION':
      return { ...state, evaluation: action.payload, isLoading: false };

    case 'COMPLETE':
      return { ...state, phase: 'completed', isLoading: false };

    case 'UPDATE_NOTES':
      return { ...state, prepNotes: { ...state.prepNotes, ...action.payload } };

    case 'SET_ERROR':
      return { ...state, error: action.payload, isLoading: false };

    default:
      return state;
  }
}

// ─── Public hook ──────────────────────────────────────────────
export function useExamState() {
  const [state, dispatch] = useReducer(reducer, initial);
  const prepTimerRef = useRef<ReturnType<typeof setInterval> | null>(null);

  // Prep room countdown — auto-advances to ready_to_record when timer expires
  useEffect(() => {
    if (state.phase !== 'prep') {
      if (prepTimerRef.current) clearInterval(prepTimerRef.current);
      return;
    }
    prepTimerRef.current = setInterval(() => dispatch({ type: 'TICK_PREP' }), 1000);
    return () => {
      if (prepTimerRef.current) clearInterval(prepTimerRef.current);
    };
  }, [state.phase]);

  const actions = {
    advanceToReady: useCallback(() => dispatch({ type: 'ADVANCE_TO_READY' }), []),
    startRecording: useCallback(() => dispatch({ type: 'START_RECORDING' }), []),
    finishRecording: useCallback((blob: Blob, url: string) =>
      dispatch({ type: 'FINISH_RECORDING', payload: { blob, url } }), []),
    setLoading: useCallback((on: boolean, message?: string) =>
      dispatch({ type: 'SET_LOADING', payload: { on, message } }), []),
    setTranscript: useCallback((text: string) =>
      dispatch({ type: 'SET_TRANSCRIPT', payload: text }), []),
    initDiscussion: useCallback((questions: string[]) =>
      dispatch({ type: 'INIT_DISCUSSION', payload: { questions } }), []),
    submitStudentAnswer: useCallback((answer: string) =>
      dispatch({ type: 'SUBMIT_STUDENT_ANSWER', payload: answer }), []),
    advanceQuestion: useCallback(() => dispatch({ type: 'ADVANCE_QUESTION' }), []),
    setEvaluation: useCallback((ev: AIEvaluation) =>
      dispatch({ type: 'SET_EVALUATION', payload: ev }), []),
    completeExam: useCallback(() => dispatch({ type: 'COMPLETE' }), []),
    updateNotes: useCallback((notes: Partial<PrepNotes>) =>
      dispatch({ type: 'UPDATE_NOTES', payload: notes }), []),
    setError: useCallback((msg: string) =>
      dispatch({ type: 'SET_ERROR', payload: msg }), []),
  };

  return { state, actions };
}
